### PR TITLE
Add async logrus hook for alert

### PR DESCRIPTION
**Pull request by wanliqun**
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36)* status: 3 of 4 files reviewed, 13 unresolved discussions (waiting on @wanliqun)

___
*[`log/hook/async.go` line 13 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLJBLOETnqjjBasMGo:-NxLJBLOETnqjjBasMGp:b-7ad090) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L13)):*
> ```Go
> )
> 
> type runningStatus uint32
> ```

`status`?

Moreover, it is overdesign to use `enum` for `bool` purpose.



_Code quote:_
```Go
runningStatus
```
___
*[`log/hook/async.go` line 30 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLJsaG6zA4ThcKwjGF:-NxLJsaG6zA4ThcKwjGG:brwk877) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L30)):*
> ```Go
> 	IdlePoolWorkers uint32 `default:"4"`
> 	// The max number of goroutines that can be running concurrently while busy.
> 	MaxConcurrentWorkers uint32 `default:"16"`
> ```

Suggest 1 thread by default to avoid rate limited by 3rd party alert service.
___
*[`log/hook/async.go` line 36 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLLy7M5j5WqtvzmDw5:-NxLKGC9AsNspcad8OAi:bjcr5b3) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L36)):*
> ```Go
> 
> // AsyncWrapper is an async wrapper that uses goroutines to invoke the wrapped hook.
> type AsyncWrapper struct {
> ```

I think `AsyncHook` is a better name.



_Code quote:_
```Go
AsyncWrapper
```
___
*[`log/hook/async.go` line 41 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLKk9W9gfTW05JCP67:-NxLKk9W9gfTW05JCP68:b-xs56o3) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L41)):*
> ```Go
> 
> 	// The flag to indicate running status: 0 - stopped, 1 - running.
> 	runningFlag uint32
> ```

Why not use `sync.Bool` instead?
___
*[`log/hook/async.go` line 54 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLMpOoAor0My8V2kTm:-NxLMpOoAor0My8V2kTn:bcyvgg) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L54)):*
> ```Go
> }
> 
> func NewAsyncWrapper(wrappedHook logrus.Hook, opts AsyncOption) *AsyncWrapper {
> ```

`hook` is the right name, since it is not be wrapped yet.



_Code quote:_
```Go
wrappedHook
```
___
*[`log/hook/async.go` line 64 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLNAoT0mdjZL5jzXEx:-NxLNAoT0mdjZL5jzXEy:b5ad4go) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L64)):*
> ```Go
> func (w *AsyncWrapper) Fire(entry *logrus.Entry) error {
> 	if !w.isRunning() {
> 		return errNotRunning
> ```

Why not starting the AsyncHook worker when instance created?
___
*[`log/hook/async.go` line 71 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLNSwuAf0cFFUJUuzT:-NxLNSwuAf0cFFUJUuzU:b-s7hdo6) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L71)):*
> ```Go
> 		return nil
> 	case <-w.ctx.Done():
> 		return w.ctx.Err()
> ```

What's the logrus behavior if error returned?

Moreover, it is OK to ignore when the `ctx` is done, which is triggered when program is terminating.
___
*[`log/hook/async.go` line 80 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLOKGk8R2n9y_CkQqT:-NxLOKGk8R2n9y_CkQqU:b-okl05d) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L80)):*
> ```Go
> 
> func (w *AsyncWrapper) Start(ctx context.Context) {
> 	if w.isRunning() { // already started?
> ```

I think the worker could be started when instance created.
___
*[`log/hook/async.go` line 107 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLPd0f-gPE59SQ7N3A:-NxLPd0f-gPE59SQ7N3B:b-b6gti6) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L107)):*
> ```Go
> }
> 
> func (w *AsyncWrapper) Stop() {
> ```

Unnecessary, since `Start` method has `ctx` parameter to indicate termination.
___
*[`log/hook/async.go` line 120 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLPkyt3S5D782JGfTX:-NxLPkyt3S5D782JGfTY:b-7mmvkp) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L120)):*
> ```Go
> 
> // boost starts extra goroutine to help empty out the job queue.
> func (w *AsyncWrapper) boost(entry *logrus.Entry) error {
> ```

It seems the design is complex because of boost mechanism. Why not only limit the maximum concurrent number of goroutines?
___
*[`log/hook/async.go` line 149 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLQ6q43_-UNVQXF6YO:-NxLQ6q43_-UNVQXF6YP:bpva7zn) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L149)):*
> ```Go
> }
> 
> func (w *AsyncWrapper) wrapCall(entry *logrus.Entry) {
> ```

`fire(entry *logrus.Entry)`?
___
*[`log/hook/async.go` line 154 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLQWMO8JdBFwTBUcpP:-NxLQWMO8JdBFwTBUcpQ:b-7keymj) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L154)):*
> ```Go
> 		entryStr, _ := formatter.Format(entry)
> 
> 		fmt.Printf("Asyn hook call error %v with entry %v\n", err, entryStr)
> ```

1) why not use json format? text format is ok.
2) how about to output to stderr?
___
*[`log/hook/hook.go` line 29 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLQgRf4WmgOlFrG5os:-NxLQgRf4WmgOlFrG5ot:b-mko4kp) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/hook.go#L29)):*
> ```Go
> 	Channels []string
> 	// async worker options
> 	Async AsyncOption
> ```

Optional to allow non-async mode?

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36)* status: 1 of 4 files reviewed, 13 unresolved discussions (waiting on @boqiu)

___
*[`log/hook/async.go` line 13 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLJBLOETnqjjBasMGo:-NxLu4u-0yonQmfeZICd:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L13)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`status`?

Moreover, it is overdesign to use `enum` for `bool` purpose.
</blockquote></details>

done
___
*[`log/hook/async.go` line 30 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLJsaG6zA4ThcKwjGF:-NxLu7NtDWsX8wDN7Hrw:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L30)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Suggest 1 thread by default to avoid rate limited by 3rd party alert service.
</blockquote></details>

done
___
*[`log/hook/async.go` line 36 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLLy7M5j5WqtvzmDw5:-NxLu87G23To8_5638lV:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L36)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

I think `AsyncHook` is a better name.
</blockquote></details>

done
___
*[`log/hook/async.go` line 41 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLKk9W9gfTW05JCP67:-NxLwhRO8nYqD-UUsq12:b-hfpv0l) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L41)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not use `sync.Bool` instead?
</blockquote></details>

removed
___
*[`log/hook/async.go` line 54 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLMpOoAor0My8V2kTm:-NxLwjH81y4YrSCJJFg5:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L54)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`hook` is the right name, since it is not be wrapped yet.
</blockquote></details>

done
___
*[`log/hook/async.go` line 64 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLNAoT0mdjZL5jzXEx:-NxLua6e5z9BLIyjRfGu:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L64)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not starting the AsyncHook worker when instance created?
</blockquote></details>

done
___
*[`log/hook/async.go` line 71 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLNSwuAf0cFFUJUuzT:-NxLuamNAxVs7KAoZES8:bogpd4k) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L71)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

What's the logrus behavior if error returned?

Moreover, it is OK to ignore when the `ctx` is done, which is triggered when program is terminating.
</blockquote></details>

Done

By default, Logrus does not do anything with this error; it does not stop the execution of other hooks or the logging statement itself. The error is typically logged to `stderr`, and the program continues to execute.
___
*[`log/hook/async.go` line 80 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLOKGk8R2n9y_CkQqT:-NxLvCtzCLQ9niwOKJa3:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L80)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

I think the worker could be started when instance created.
</blockquote></details>

done
___
*[`log/hook/async.go` line 107 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLPd0f-gPE59SQ7N3A:-NxLvF6aAK_jfrNqpTE2:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L107)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Unnecessary, since `Start` method has `ctx` parameter to indicate termination.
</blockquote></details>

done
___
*[`log/hook/async.go` line 120 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLPkyt3S5D782JGfTX:-NxLvGMM3h7dJPCIof8J:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L120)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

It seems the design is complex because of boost mechanism. Why not only limit the maximum concurrent number of goroutines?
</blockquote></details>

done
___
*[`log/hook/async.go` line 149 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLQ6q43_-UNVQXF6YO:-NxLvHHT6tw1bhqNJ2mo:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L149)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`fire(entry *logrus.Entry)`?
</blockquote></details>

done
___
*[`log/hook/async.go` line 154 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLQWMO8JdBFwTBUcpP:-NxLvHwrBAeJ9rKu64ao:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/async.go#L154)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

1) why not use json format? text format is ok.
2) how about to output to stderr?
</blockquote></details>

done
___
*[`log/hook/hook.go` line 29 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxLQgRf4WmgOlFrG5os:-NxLvIc51uFfVDVOD3Cm:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/c46b41ffbcd26b2891c673f7cffcaf469c1223ae/log/hook/hook.go#L29)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Optional to allow non-async mode?
</blockquote></details>

done

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36)* status: all files reviewed, 7 unresolved discussions (waiting on @wanliqun)

___
*[`log/log.go` line 45 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxMGr12EuAnlUjcbdJ4:-NxMGr12EuAnlUjcbdJ5:bqk8k0x) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/log.go#L45)):*
> ```Go
> 	logrus.SetLevel(level)
> 
> 	err = hook.AddAlertHook(context.Background(), conf.AlertHook)
> ```

Better to allow client to specify a `context` for graceful termination. Otherwise, minor logs may be missed for notification.

BTW, it is important to specify a suitable timeout to send notification to dingtalk or telegram.
___
*[`log/hook/async.go` line 16 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxMHmCS0Onlq8NfO9mJ:-NxMHmCS0Onlq8NfO9mK:bd0zvza) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/hook/async.go#L16)):*
> ```Go
> type AsyncOption struct {
> 	// Enable async mode or not
> 	Enabled bool
> ```

How about to leverage `MaxWorkers` variable to decide if async hook enabled?

`MaxWorkers == 0` indicates async hook disabled.
___
*[`log/hook/async.go` line 18 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxMKKm90QIk9pt84-V5:-NxMKKm90QIk9pt84-V6:bjd0e74) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/hook/async.go#L18)):*
> ```Go
> 	Enabled bool
> 	// The max number of worker goroutines that can be running concurrently.
> 	MaxWorkers uint32 `default:"4"`
> ```

Better to use 1 by default, so as  to send alerts in sequence.
___
*[`log/hook/async.go` line 23 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxMILySBLUpiaxcqlSH:-NxMILySBLUpiaxcqlSI:b-d6hu9l) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/hook/async.go#L23)):*
> ```Go
> }
> 
> // AsyncHook is an async wrapper that uses goroutines to invoke the wrapped hook.
> ```

// AsyncHook allows to handle `logrus.Hook` asynchronously.
___
*[`log/hook/async.go` line 33 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxMIzuf8mfE4J3spgMO:-NxMIzuf8mfE4J3spgMP:bjqk97d) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/hook/async.go#L33)):*
> ```Go
> 	jobQueue chan *logrus.Entry
> 	// The context for life cycle control.
> 	ctx context.Context
> ```

Could be removed and add a `ctx` parameter for `start` method.

The less struct fields, the better.
___
*[`log/hook/async.go` line 88 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxMKfepCZVR9-q2aOXi:-NxMKfepCZVR9-q2aOXj:b-re70bj) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/hook/async.go#L88)):*
> ```Go
> 	if h.incrWorkerCounter() > h.MaxWorkers {
> 		h.decrWorkerCounter()
> 		return errors.New("async hook buffer is full")
> ```

Is it possible to notify that send queue is full and requires administrator to check logs in time?
___
*[`log/hook/async.go` line 92 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxML2pj8gzQ1WJd0SoH:-NxML2pj8gzQ1WJd0SoI:bzf3fbt) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/hook/async.go#L92)):*
> ```Go
> 
> 	go func() {
> 		defer h.decrWorkerCounter()
> ```

In my mind, such boost design is not good enough. Instead, I suggest one thread for one channel, and send alerts in sequence. Once channel buffer is not enough, just notify admin to check logs in time (even such message will not be delivered in  time).

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @boqiu)

___
*[`log/log.go` line 45 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxMGr12EuAnlUjcbdJ4:-NxWtb3Y-hP9KrOgz5Cf:b-qiy6wj) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/log.go#L45)):*
> Better to allow client to specify a `context` for graceful termination. Otherwise, minor logs may be missed for notification.

Done

> BTW, it is important to specify a suitable timeout to send notification to dingtalk or telegram.
Good point. it's also an important consideration for both sync and async mode. Besides, due to the `dingtalk` sdk we've used doesn't support timeout operation, I will submit a separate PR to fix it.
___
*[`log/hook/async.go` line 16 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxMHmCS0Onlq8NfO9mJ:-NxMk_8sDcbA1Oc_LSpl:bb6un1j) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/hook/async.go#L16)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to leverage `MaxWorkers` variable to decide if async hook enabled?

`MaxWorkers == 0` indicates async hook disabled.
</blockquote></details>

Done
___
*[`log/hook/async.go` line 18 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxMKKm90QIk9pt84-V5:-NxWuIb604IAf90TtRGb:bb6un1j) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/hook/async.go#L18)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Better to use 1 by default, so as  to send alerts in sequence.
</blockquote></details>

Done
___
*[`log/hook/async.go` line 23 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxMILySBLUpiaxcqlSH:-NxWuJ_OEeWgRMwyCnF1:bb6un1j) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/hook/async.go#L23)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

// AsyncHook allows to handle `logrus.Hook` asynchronously.
</blockquote></details>

Done
___
*[`log/hook/async.go` line 33 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxMIzuf8mfE4J3spgMO:-NxWuKPx03E3ZQFn06Hh:bb6un1j) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/hook/async.go#L33)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Could be removed and add a `ctx` parameter for `start` method.

The less struct fields, the better.
</blockquote></details>

Done
___
*[`log/hook/async.go` line 88 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxMKfepCZVR9-q2aOXi:-NxWuLWX5ajJ3S0nF-4L:b-3cwtue) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/hook/async.go#L88)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is it possible to notify that send queue is full and requires administrator to check logs in time?
</blockquote></details>

I've switched to notify the conjestion status synchronously to the alert channel, which should be enough for current stage.
___
*[`log/hook/async.go` line 92 at r3](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxML2pj8gzQ1WJd0SoH:-NxWvEVBD8qBEfBpDONR:bb6un1j) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4568602b6bcfcd09ef5f1b080866f988806b0f7e/log/hook/async.go#L92)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

In my mind, such boost design is not good enough. Instead, I suggest one thread for one channel, and send alerts in sequence. Once channel buffer is not enough, just notify admin to check logs in time (even such message will not be delivered in  time).
</blockquote></details>

Done

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36)* status: all files reviewed, 2 unresolved discussions (waiting on @wanliqun)

___
*[`config/config.go` line 17 at r4](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxWz8218XhjT_A_uWe8:-NxWz8218XhjT_A_uWe9:b7wxk8h) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/13a2e04a586ba2f27aeb60299a49c001e1d56751/config/config.go#L17)):*
> ```Go
> //
> // Note that it will panic and exit if any error happens.
> func MustInit(ctx context.Context, wg *sync.WaitGroup, viperEnvPrefix string) {
> ```

Suggest to add a new method for graceful shutdown.
___
*[`log/hook/async.go` line 77 at r4](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxX-cvK6UaHXcRv8TJa:-NxX-cvK6UaHXcRv8TJb:b-nel2br) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/13a2e04a586ba2f27aeb60299a49c001e1d56751/log/hook/async.go#L77)):*
> ```Go
> 		defer wg.Done()
> 
> 		var awg sync.WaitGroup
> ```

Why not reuse `wg`?

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36)* status: all files reviewed, 2 unresolved discussions (waiting on @boqiu)

___
*[`log/hook/async.go` line 77 at r4](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxX-cvK6UaHXcRv8TJa:-NxX2Dpu2rib2WkHkqOp:b-i1nqol) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/13a2e04a586ba2f27aeb60299a49c001e1d56751/log/hook/async.go#L77)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not reuse `wg`?
</blockquote></details>

`
// start launches worker goroutines and manages their lifecycle.
func (h *AsyncHook) start(ctx context.Context, wg *sync.WaitGroup) {
  defer h.started.Store(true) // Mark the hook as started.

  wg.Add(1)
  go func() {
    defer wg.Done()

    var awg sync.WaitGroup
    for i := 0; i < h.NumWorkers; i++ {
      awg.Add(1)
      go func() {
        defer awg.Done()
        h.worker(ctx)
      }()
    }

    awg.Wait()
    h.drainJobQueue()
  }()
}`
I'm afriad we can't as the `wg` is passed in as a parameter, and we can't guaratee it isn't used somewhere else. Under such case the `wg.Wait()` might cause a dead lock.

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @boqiu)

___
*[`config/config.go` line 17 at r4](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxWz8218XhjT_A_uWe8:-NxkXuATA-0qZNihMMpx:b-896fix) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/13a2e04a586ba2f27aeb60299a49c001e1d56751/config/config.go#L17)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Suggest to add a new method for graceful shutdown.
</blockquote></details>

Done.

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36)* status: all files reviewed, 1 unresolved discussion (waiting on @wanliqun)

___
*[`graceful/handler.go` line 1 at r5](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxkX7XD3N_9eFCMTYDO:-NxkX7XE5TZxHDhgXqNB:b-tnylkp) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/7901be7b7b0690a245ca19e1c1538479069111c7/graceful/handler.go#L1)):*
> ```Go
> package graceful
> ```

`terminate` or `shutdown` is better.



_Code quote:_
```Go
graceful
```

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @boqiu)

___
*[`graceful/handler.go` line 1 at r5](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NxkX7XD3N_9eFCMTYDO:-NxpoAY86tZNg0LjDXnC:b-896fix) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/7901be7b7b0690a245ca19e1c1538479069111c7/graceful/handler.go#L1)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`terminate` or `shutdown` is better.
</blockquote></details>

Done.

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36)* status: all files reviewed, 1 unresolved discussion (waiting on @wanliqun)

___
*[`terminate/context.go` line 1 at r7](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36#-NyPkClrBbGQX82X_Ych:-NyPkClrBbGQX82X_Yci:bfr5hxs) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/4363dbd3d4d6067d971fd3249818fce590338dfd/terminate/context.go#L1)):*
> ```Go
> package terminiate
> ```

Not used?

**Review by boqiu — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/36)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wanliqun)

**Pull request merged**
