### PR TITLE
Add `TolerantLogger` to tolerate error retries.

### PR DESCRIPTION
**Pull request by wanliqun**
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20)* status: all files reviewed, 2 unresolved discussions (waiting on @wangdayong228 and @wanliqun)

___
*[`log/tolerant_logger.go` line 17 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20#-Nlbg1VG0GqorSbrIkoB:-Nlbg1VG0GqorSbrIkoC:bb7bfok) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/f62de08effe74924c30193f29468cb525efe7a28/log/tolerant_logger.go#L17)):*
> ```Go
> 
> func NewTolerantLogger(errorLimit int) *TolerantLogger {
> 	if errorLimit == 0 {
> ```

`<=`
___
*[`log/tolerant_logger.go` line 35 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20#-NlbgWwxAUmU_kWS2HyA:-NlbgWwxAUmU_kWS2HyB:b-kqb1ga) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/f62de08effe74924c30193f29468cb525efe7a28/log/tolerant_logger.go#L35)):*
> ```Go
> 		logger.WithField("errCount", errCnt).Errorf(msg, args...)
> 	}
> }
> ```

How about to support warning level logs as well?

**Comment by wanliqun** [comment]
*[`log/tolerant_logger.go` line 17 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20#-Nlbg1VG0GqorSbrIkoB:-NlvgZih6z_UpW9i2XKY:bkhikc8) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/f62de08effe74924c30193f29468cb525efe7a28/log/tolerant_logger.go#L17)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`<=`
</blockquote></details>

deprecated

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @boqiu and @wangdayong228)

___
*[`log/tolerant_logger.go` line 35 at r1](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20#-NlbgWwxAUmU_kWS2HyA:-NlvgbWu1V8az4WW37JY:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/f62de08effe74924c30193f29468cb525efe7a28/log/tolerant_logger.go#L35)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

How about to support warning level logs as well?
</blockquote></details>

done

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20)* status: all files reviewed, 3 unresolved discussions (waiting on @wangdayong228 and @wanliqun)

___
*[`log/tolerant_logger.go` line 24 at r2](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20#-NlvlTgQ3DLKhIXZeZgo:-NlvlTgQ3DLKhIXZeZgp:blvln2d) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/e22b6f5ebcc806055ffb54bac2f4377fbbf7b555/log/tolerant_logger.go#L24)):*
> ```Go
> // the continuous error count.
> type ErrorTolerantLogger struct {
> 	*ErrorToleranceConfig
> ```

Is it necessary to export `config`?
___
*[`log/tolerant_logger.go` line 29 at r2](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20#-NlvlY976sxvNG5VNVW_:-NlvlY976sxvNG5VNVWa:b-yoxvdx) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/e22b6f5ebcc806055ffb54bac2f4377fbbf7b555/log/tolerant_logger.go#L29)):*
> ```Go
> }
> 
> func NewErrorTolerantLogger(opts ...func(*ErrorTolerantLogger)) *ErrorTolerantLogger {
> ```

Suggest to remove such `builder` design pattern to simplify code. Just allow user to pass in a config of value type.
___
*[`log/tolerant_logger.go` line 77 at r2](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20#-NlvmFWE47-ru1clPfZG:-NlvmFWE47-ru1clPfZH:bu091c3) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/e22b6f5ebcc806055ffb54bac2f4377fbbf7b555/log/tolerant_logger.go#L77)):*
> ```Go
> 
> // Log logs the error message with appropriate level based on the continuous error count.
> func (l *ErrorTolerantLogger) Log(err error, logf func(logrus.Level)) {
> ```

Suggest not to over design with a method pointer. Instead, a logrus logger instance is enough and simple.

**Review by wanliqun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @boqiu and @wangdayong228)

___
*[`log/tolerant_logger.go` line 24 at r2](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20#-NlvlTgQ3DLKhIXZeZgo:-NlvtGSiCVXTTRWR_aqy:b-pv1xxt) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/e22b6f5ebcc806055ffb54bac2f4377fbbf7b555/log/tolerant_logger.go#L24)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is it necessary to export `config`?
</blockquote></details>

hidden
___
*[`log/tolerant_logger.go` line 29 at r2](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20#-NlvlY976sxvNG5VNVW_:-NlvtJ6J7cszK_SkThgd:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/e22b6f5ebcc806055ffb54bac2f4377fbbf7b555/log/tolerant_logger.go#L29)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Suggest to remove such `builder` design pattern to simplify code. Just allow user to pass in a config of value type.
</blockquote></details>

done
___
*[`log/tolerant_logger.go` line 77 at r2](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20#-NlvmFWE47-ru1clPfZG:-NlvtKQN3FWcGhE8nYPT:bb7f2mf) ([raw file](https://github.com/Conflux-Chain/go-conflux-util/blob/e22b6f5ebcc806055ffb54bac2f4377fbbf7b555/log/tolerant_logger.go#L77)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Suggest not to over design with a method pointer. Instead, a logrus logger instance is enough and simple.
</blockquote></details>

done

**Review by boqiu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/go-conflux-util/20#-:-Nlvu78YEwW_EDt0flnP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wangdayong228)

**Pull request merged**
